"""Generate device-sized BMFonts for the four selectable families (Pillow)."""
import json
import os
from pathlib import Path
import xml.etree.ElementTree as ET
import zipfile

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]


def generate(folder, name, chars, height, max_width=None, font_path=None):
    size = height * 2
    while True:
        font = ImageFont.truetype(str(font_path or ROOT / "assets/fonts/college.ttf"), size)
        top = min(font.getbbox(c)[1] for c in chars if c != " ")
        bottom = max(font.getbbox(c)[3] for c in chars if c != " ")
        widest_time = max(font.getlength(c) for c in "0123456789") * 4 + font.getlength(":")
        if bottom - top <= height and (max_width is None or widest_time <= max_width):
            break
        size -= 1
    line_height = bottom - top
    if max_width is not None:
        assert max(round(font.getlength(c)) for c in "0123456789") * 4 + round(font.getlength(":")) <= max_width + 3
    atlas = Image.new("RGBA", (256, 512))
    draw = ImageDraw.Draw(atlas)
    x, y, row = 1, 1, 0
    entries = []
    for c in chars:
        left, upper, right, lower = font.getbbox(c)
        w, h = max(1, right - left), max(1, lower - upper)
        if x + w + 1 > 256:
            x, y, row = 1, y + row + 1, 0
        assert y + h < 512
        draw.text((x - left, y - upper), c, font=font, fill="white")
        entries.append(f"char id={ord(c)} x={x} y={y} width={w} height={h} xoffset={left} yoffset={upper-top} xadvance={round(font.getlength(c))} page=0 chnl=15")
        x += w + 1
        row = max(row, h)
    atlas = atlas.crop((0, 0, 256, y + row + 1))
    atlas.save(folder / f"{name}.png")
    (folder / f"{name}.fnt").write_text(
        f'info face="{name}" size={size} bold=0 italic=0 charset="" unicode=1 stretchH=100 smooth=1 aa=1 padding=0,0,0,0 spacing=1,1\n'
        f'common lineHeight={line_height} base={line_height} scaleW=256 scaleH={atlas.height} pages=1 packed=0\n'
        f'page id=0 file="{name}.png"\nchars count={len(entries)}\n' + "\n".join(entries) + "\n", encoding="utf-8")


def main():
    originals = ROOT / "assets/fonts"
    originals.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(ROOT / "college.zip") as archive:
        for name in ("college.ttf", "college.txt", "license.txt"):
            (originals / name).write_bytes(archive.read(name))
    families = {"College": originals / "college.ttf"}
    for family, zip_name, member in [
        ("BreeSerif", "bree-serif.zip", "BreeSerif-Regular.ttf"),
        ("Gorditas", "gorditas.zip", "Gorditas-Regular.ttf"),
        ("Lumberjack", "lumberjack.zip", "Lumberjack/Lumberjack.otf"),
    ]:
        dest = originals / family
        dest.mkdir(exist_ok=True)
        with zipfile.ZipFile(originals / zip_name) as archive:
            for entry in archive.namelist():
                if entry == member or entry.lower().endswith((".txt", ".pdf")):
                    (dest / Path(entry).name).write_bytes(archive.read(entry))
        families[family] = dest / Path(member).name
    devices = Path(os.environ["APPDATA"]) / "Garmin/ConnectIQ/Devices"
    products = ET.parse(ROOT / "manifest.xml").findall(".//{*}product")
    widths = {}
    for product in products:
        device = product.attrib["id"]
        config = json.loads((devices / device / "compiler.json").read_text(encoding="utf-8"))
        widths[device] = int(config["deviceFamily"].split("-")[-1].split("x")[0])
    for width in sorted(set(widths.values())):
        folder = ROOT / f"resources-college-{width}/fonts"
        folder.mkdir(parents=True, exist_ok=True)
        specs = [("CollegeTime", "0123456789:", int(width * .22)),
                 ("CollegeValue", "0123456789.,-%K", int(width * .08)),
                 ("CollegeSmall", "0123456789.,-%K", max(8, int(width * .042))),
                 ("CollegeLabel", " ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789", int(width * .08))]
        names = []
        for family, font_path in families.items():
            for original_name, chars, height in specs:
                name = original_name.replace("College", family)
                generate(folder, name, chars, height, width * .77 if name.endswith("Time") else None, font_path)
                names.append(name)
        (folder / "fonts.xml").write_text("<fonts>\n" + "".join(f'    <font id="{name}" filename="{name}.fnt" />\n' for name in names) + "</fonts>\n", encoding="utf-8")
    jungle = ROOT / "monkey.jungle"
    original = jungle.read_text().split("# College font resources")[0].rstrip()
    jungle.write_text(original + "\n\n# College font resources (generated by scripts/generate_college_fonts.py)\n" + "".join(f"{device}.resourcePath = $(base.resourcePath);resources-college-{width}\n" for device, width in widths.items()), encoding="utf-8")
    # Reapply per-device field settings after rebuilding resourcePath entries.
    from generate_device_settings import generate
    generate(devices)
    print(f"Generated and checked {len(families)} font families for {len(widths)} devices: {sorted(set(widths.values()))}")


if __name__ == "__main__":
    main()

